### ISSUE TITLE
Jira's track time goes back to default after changing project

### ISSUE THREAD

**Issue by rconcepcion88** [Strategery-Inc/jira-harvest-time-tracker#100]
**Describe the bug**

**To Reproduce**

1. Click Track Time in Jira

2. Change the second dropdown to something other than the first one
![image](https://user-images.githubusercontent.com/61593145/75563216-993ad380-5a0f-11ea-9b21-3218ba3479a5.png)

3. Change the project to something else
![image](https://user-images.githubusercontent.com/61593145/75563286-bb345600-5a0f-11ea-9c92-668d1485ea46.png)

4. Note that second dropdown still shows selection in step 2
![image](https://user-images.githubusercontent.com/61593145/75563318-c8e9db80-5a0f-11ea-921e-70ab3f4caeaa.png)

5. Put value in time and click Save and Log
![image](https://user-images.githubusercontent.com/61593145/75563405-ea4ac780-5a0f-11ea-8262-32c443ff3214.png)

6. Go to Harvest, it will have logged default (1st select option) of second dropdown instead of the one being shown.
![image](https://user-images.githubusercontent.com/61593145/75563475-08b0c300-5a10-11ea-88e6-0c6c85b0f456.png)

**Expected behavior**
Harvest should log the time to correct bucket as shown on the screen

**Screenshots**
If applicable, add screenshots to help explain your problem. Be careful to blur or paint over any sensitive information. If you prefer, you can instead email them to support (at) strategery (dot) io
![image](https://user-images.githubusercontent.com/61593145/75563200-917b2f00-5a0f-11ea-870c-500d6af3b965.png)

**Browser Console Logs**
After reporting the issue, whenever possible, please send us an email to support (at) strategery (dot) io including your [browser console log](https://kb.mailster.co/how-can-i-open-the-browsers-console/) output when the error happened. This will help us find the issue much faster and provide an accurate bug fix.

**Please complete the following information:**
 - JIRA Type: Server
 - JIRA Version: 8.5
 - Browser Type: chrome
 - Browser Version:  80.0.3987.122

**Additional context**

**Comment by gsomoza** [comment]
Thanks for the report! We'll take a look asap.

**Comment by gsomoza** [comment]
Quick update: we were able to duplicate the issue and we're about to release a fix.

**Comment by gsomoza** [comment]
The potential fix was release last week. @rconcepcion88  could you please confirm if this worked for you?

**Comment by gsomoza** [comment]
Another customer confirmed this issue is fixed. Thanks again for reporting the bug! Will close the ticket for now.
