### ISSUE TITLE
Not able to connect

### ISSUE THREAD

**Issue by ksartain** [Strategery-Inc/jira-harvest-time-tracker#103]
![Screen Shot 2020-07-27 at 1 13 28 PM](https://user-images.githubusercontent.com/33069113/88571008-01b3ce00-d00b-11ea-8a9a-3f06cfaff28a.png)

Our team is getting this error message when trying to track time.

**Comment by gsomoza** [comment]
Thanks for reporting. Could you please email me the following information? 
* Your Atlassian SEN / license number
* A copy if your browser's Console output (found within Developer Tools). Feel free to filter out any lines that may include sensitive information.
* A copy of any errors in the "Network" tab (also within Developer Tools), as well as any requests to the `cloud.harvest-jira.strategery.io` domain

Please address the email to `support (at) strategery (dot) io`

**Comment by gsomoza** [comment]
Could you please also verify if you can load the following URL using the same browser with which you had the issue? https://cloud.harvest-jira.strategery.io/v1/atlassian-connect.json

**Comment by ksartain** [comment]
It seems like everything went back to functioning properly an hour or so
after my reported ticket.

Thanks for the follow up!
-- 
Kristin Sartain
Director of Projects
804-366-8639
www.kalamuna.com

**Comment by gsomoza** [comment]
Glad to hear that and thanks for the update!

**Comment by gsomoza** [comment]
FYI we didn't change anything on our end, so I'm not sure what could have caused it. It could have been a temporary outage in AWS (what we use to host our files) but I'm not sure about that either...
