### ISSUE TITLE
Time can't be adjusted once a timer has begun?

### ISSUE THREAD

**Issue by sdishman** [Strategery-Inc/jira-harvest-time-tracker#14]
Perhaps I'm missing something, but here is the use case I'm struggling with at this very moment:

I started a timer via JIRA about an hour ago.  I finished the work on that timer about a half-hour ago, and started working on something else but forgot to stop the timer.

When I go to stop the timer, I'd like to manually set the End time to a half-hour ago so that it logs work appropriately.  However, it appears that the field is disabled and there's nothing I can do except click "Stop Timer".

This means it's going to create an inaccurately long Work Log entry that I'm going to have to remove (along with the time entry itself) and start over, which is a hassle.

This is related to #12 in that both issues expose pain points caused by simple mistakes that people might make when logging their time.  Obviously the best practice is to be militant about updating what you're working on and never making a mistake in tracking, but the truth is that people will occasionally slip up and it would be extremely helpful if we could recover gracefully from that.

**Comment by kuya1284** [comment]
I just wanted to drop a comment that with the Duration setting, the workaround that Gabriel mentioned is exactly what we've had to do. In addition, if needed, we would also manually edit the worklog entry in JIRA as well. I never noticed the Time Settings option. I'll have to play around with that. Thanks for pointing that out. (I wonder what impact this would have on the Google Chrome Extension if I were to change it to Start/End Times).
