### ISSUE TITLE
Plugin requires me to login to Harvest far too frequently

### ISSUE THREAD

**Issue by sdishman** [Strategery-Inc/jira-harvest-time-tracker#16]
I don't have a handle on what's causing this, or even how to reproduce it reliably, but what I do know is that the new version of this plugin requires me to login to Harvest far more often than the previous version did.

Previously, it seemed that if I had a valid Harvest session in another browser tab, then the plugin never seemed to have a problem.  However, I've tried creating several timers today, and I've had to login with almost every new timer.  Sometimes only minutes have passed between attempts to use the plugin.

**Comment by cprieto741** [comment]
Hi,
Do you have an update on this ticket?

**Comment by gabrielsomoza** [comment]
Not yet, we're doing this as part of a big re-design of the plugin so it will take a while longer..

**Comment by gabrielsomoza** [comment]
Closing this ticket because we'll start work on refactoring session management, which will include a fix for this. Please follow further updates on #44
