### ISSUE TITLE
Plugin is not as good at "remembering" the correct Harvest Project/Task as it used to be

### ISSUE THREAD

**Issue by sdishman** [Strategery-Inc/jira-harvest-time-tracker#17]
In the previous version of the plugin (which we have been using for a long while, and loved, other than the lack of Work Log integration), it seemed to do a really good job of remembering which Harvest project should be used.  Our Harvest projects are somewhat correlated to our JIRA projects, and it seemed that before, when I would track time on an issue for (Harvest) Project X, and then I switched to another JIRA issue in the same project and began tracking time, the plugin initially selected (Harvest) Project X, which was a really good thing.  It was also pretty good about remembering the appropriate (Harvest) task to choose.

Now, it seems that it is very poor at both of these things.  For example, I just tracked time against an issue this morning, and then returned to work on it again.  Upon creating a second timer, the Project and Task are forgotten and I have to go hunt for the correct values again.  Since we have a lot of these, it's time-consuming and frustrating.

I will mention that when trying to create this second timer I did have to login to Harvest again (via the plugin - see #16), so perhaps that is related to why it "forgot" what Project/Task to use?

**Comment by benglass** [comment]
:+1:

**Comment by gabrielsomoza** [comment]
Closing this ticket because we'll start work on refactoring session management, which will include a fix for this. Please follow updates on #44
