### ISSUE TITLE
Permissions: Make time tracking button visibility dependend from permissions

### ISSUE THREAD

**Issue by jraduenz** [Strategery-Inc/jira-harvest-time-tracker#29]
Hi,
in our JIRA we have projects for internal development and some for support tickets. While all internal users should see this field, customers should not.
I would suggest to make time tracking button visibility depend on group membership. This group should be configured in admin backend.
Thanks,
Julian

**Comment by gabrielsomoza** [comment]
We'll add a permission (or similar setting) that will allow Admins to choose which users will see the tracker and which won't.

**Comment by gsomoza** [comment]
It's unlikely we'll implement this feature because most use-cases can be covered on the Harvest configuration. We'll re-open if we see more customers are interested in it.
