### ISSUE TITLE
Add commands to period menu for time tracker

### ISSUE THREAD

**Issue by zenchicken** [Strategery-Inc/jira-harvest-time-tracker#30]
It would be awesome if the plugin could add its own commands to the period (.) menu to quickly start/stop the timer from an issue detail screen.

![screen shot 2014-10-07 at 10 51 04 am](https://cloud.githubusercontent.com/assets/11179/4545333/1756d774-4e3a-11e4-8350-5148a8767ea2.png)

**Comment by gsomoza** [comment]
We won't pursue this feature because there's no easy way to make it cross-platform (Server / Cloud). Closing, at least for now..
