### ISSUE TITLE
Ability to track time from JIRA Agile Boards

### ISSUE THREAD

**Issue by benglass** [Strategery-Inc/jira-harvest-time-tracker#38]
We use jira kanban boards to visualize our priority tasks across projects and when working on a sprint. When you click on an issue and it opens in the sidebar of the board page the harvest track time button is not available which  means we have to go to the task detail page to start a timer. Is it possible to have the button appear in this view?

**Comment by gabrielsomoza** [comment]
Yes, in fact its in our roadmap. I'll update you here when its out (no ETA yet).

**Comment by kellaferr24** [comment]
this really needs to be addressed. How can you have integration with a time tracking tool that doesn't track directly to JIRA time tracking as well?! This is horrible for agile development and sprint planning

**Comment by gabrielsomoza** [comment]
Our tool does track directly into JIRA. Just not through the Agile view, and there are technical reasons why this was (and still is) a delicate and difficult task, including the fact that JIRA Agile is not really engineered to be easily extensible.

However we recently released a version that allows you to track time on tickets by clicking a button in the Agile view. Its as far as we can go right now with the current JIRA Agile limitations. @benglass could you take a look and let us know what you think?

@kellaferr24  on another note, I've seen your comment on another ticket as well and sense a general tone of frustration. I'm sorry if that's the case. We'd be happy to hear about any other issues you may be having and see what we can do to help you through them, so for further assistance please feel free to email us directly at: contact (at) usestrategery (dot) com
