### ISSUE TITLE
Harvest app hostname no longer remembered.

### ISSUE THREAD

**Issue by vdwrcarlson** [Strategery-Inc/jira-harvest-time-tracker#39]
Hello, since upgrading the plugin to 2.5.0, the Harvest hostname is no longer remembered in the popup form that appears when starting to track time on an issue, and we have to type it in manually each day. Was this caused by the upgrade? If so, can this functionality be brought back?

**Comment by gabrielsomoza** [comment]
Related to #17 - could you subscribe to that ticket to get updates?

**Comment by vdwrcarlson** [comment]
Thanks Gabriel,

However, I want to be sure it's clear that I'm referring to a new 
problem in 2.5.0 where it does not remember the harvestapp.com hostname 
when first logging in. So it's a distinct issue from the one in #17 
where it doesn't remember task/project associations. That issue has 
existed for some time prior to this hostname problem.

I imagine you realize that, just want to be sure I'm being clear.

-Ross

**Comment by gabrielsomoza** [comment]
Yes, that's clear - I'm linking it to #17 simply because we'll tackle both of them together. Don't forget to subscribe to that ticket in order to get updates.
