### ISSUE TITLE
Improve Harvest Session Management

### ISSUE THREAD

**Issue by gsomoza** [Strategery-Inc/jira-harvest-time-tracker#44]
Right now we're saving Harvest session info into the JIRA session. This seems to cause all kinds of trouble for different users:
- https://github.com/Strategery-Inc/jira-harvest-time-tracker/issues/43
- https://github.com/Strategery-Inc/jira-harvest-time-tracker/issues/16
- https://github.com/Strategery-Inc/jira-harvest-time-tracker/issues/17

Re-implement Harvest sessions using JIRA best-practices and fix those issues so that sessions are stable. The workflow should ideally be:

A) Plugin is installed. The Admin is encouraged to configure the plugin through a popup.

B) Admin configures the Harvest endpoint / URL to which the plugin will connect. 
1. This is currently on the login popup (so each developer can choose it independently) but we need to make it a system-wide setting. I'd like to allow admins to configure multiple Harvest endpoints and select a default one. Make sure we don't run into this issue: #42 
2. Then a JIRA developer would see a drop-down at the login form (instead of a text-box) where he can select which endpoint to login to.

C) A JIRA developer goes to a ticket and logs in to Harvest by choosing an endpoint and providing a username and password. It would be great if we could encrypt this information and store it attached to the JIRA User, so that even if he logs out, once he logs back in he would be immediately connected to Harvest again.

D) The JIRA developer should still be able to logout anytime, so the logout button should stay where it is and it should remove any data associated with that user.

**Comment by sdishman** [comment]
This sounds exciting and will be a really huge help for our organization.  I'm particularly interested in part B1, where developers won't have to type in an endpoint anymore.  This is a constant frustration for our whole team.  I've tried to get around it by saving that data in LastPass, but it is very flaky and seems to have stopped working for me entirely.

**Comment by gabrielsomoza** [comment]
Yeah, LastPass sucks at that... These changes should definitely improve user experience considerably and also fix many secondary issues we have related to sessions.

**Comment by chris5287** [comment]
+1 any update available on this task?

**Comment by andrewmallis** [comment]
Our team quotes time and time again the session funk in #16 as the annoying part of our entire organizational workflow. 

Please act more quickly on this, or provide some updates.

This issue is not very [I-N-V-E-S-T](https://en.wikipedia.org/wiki/INVEST_(mnemonic)) and I fear it will never get done.

I imagine the plug in is not a huge revenue driver, but but it is a paid plug in. I can't pretend to understand what is involved with maintaining this plug in, but I do expect more action.

**Comment by chris5287** [comment]
Any updates on when this feature may be implemented?

**Comment by gsomoza** [comment]
Not much progress yet, at least not on the positive sense. I've been asking for quotes from different developers (since I can't get to this myself) and the cheapest I got so far is $15k, because general consensus is that we should re-write the plugin from scratch - and I agree with that too. 

We're currently hardly breaking even with maintenance on the plugin vs sales, so saving money for that project will take time.

So this is unlikely to happen anytime soon, at least until I'm able to set apart a whole month or so to work on it full-time and get a new version out. I'm hoping I can do this sometime this year but I'm not going to promise that..

I'm open to suggestions.

**Comment by chris5287** [comment]
Thanks for the update. Any chance of adding the source code here to GitHub so other dev's could contribute?

**Comment by gsomoza** [comment]
If you're interested in doing this I'm sure we can arrange something, you can email me at contact (at) strategery (dot) io

**Comment by gsomoza** [comment]
Closing because this was fixed/improved after the re-write of the plugin.
