### ISSUE TITLE
Display the Log Work screen after stopping the timer

### ISSUE THREAD

**Issue by kuya1284** [Strategery-Inc/jira-harvest-time-tracker#48]
Rather than automatically creating a worklog, I think a better user experience would be to trigger the Log Work screen to appear with the Time Spent field already pre-populated. This will give users the ability to add their worklog notes, as well as comments that could appear on the Comments tab. 

Currently, my (annoying and cumbersome) workflow is to
- Start the timer
- Work
- Stop the timer
- Click the Work Log tab
- Edit the entry created by the add-on and add my comments
- Copy those same comments to my clipboard
- Save my worklog entry
- Click Comment button to add a new comment, paste the same comments, then save

All this could easily be done in one shot simply by triggering the Log Work screen after stopping the timer.

**Comment by gabrielsomoza** [comment]
Thanks for the great suggestion. My current understanding is that pre-filling the form would be close to impossible with the current JIRA API, so that's why it wasn't done like this originally. But we'll look into it anyway, I can see why this would be a better approach for everyone.

**Comment by kuya1284** [comment]
Would it be possible to target the field via Javascript?

**Comment by gabrielsomoza** [comment]
That would be very unstable (a small change on their end would make things blow up), but we'll investigate if there's a reliable way to do it.

**Comment by gsomoza** [comment]
Unfortunately there's no reliable way to do this right now, it would introduce instability to the system at several levels. Closing for now, at least until a better approach is available.. thanks for the suggestion!
