### ISSUE TITLE
Change Button Title to "Submit" When Manually Tracking Time

### ISSUE THREAD

**Issue by gsomoza** [Strategery-Inc/jira-harvest-time-tracker#49]
In the popup, the user can track time manually by entering an amount of time in the corresponding text-box (e.g. "0:30" for 30 minutes) and then clicking on the "Start Tracking" button.

However, this is a bit confusing because the system doesn't really "Start Tracking": it just adds a new time-entry with a fixed time equal to the amount the user manually entered.

*Feature*
Whenever the user manually enters an amount of time using the text-box, change the blue button's label to "Submit" instead of "Start Tracking".

**Comment by gabrielsomoza** [comment]
Comes from #32

**Comment by fuhrmans** [comment]
Hi Gabriel,

Great app, thank you.  We just purchased our license after the evaluation.  I am seeing an issue with my Jira-Harvest Version 2.5.3 add-on where the Start Timer button is not changing to "Submit" when time is being entered in manually. 

See Screenshot
![2015-11-17_16-37-27](https://cloud.githubusercontent.com/assets/15899096/11228791/8f78ad52-8d4c-11e5-91f1-70828d20ae90.png)

What additional information do you need from me to troubleshoot?  Thanks for your help!  Steve
