### ISSUE TITLE
Work Log must use the Harvest Start Time instead of Stop Time in JIRA's Date Started field

### ISSUE THREAD

**Issue by kuya1284** [Strategery-Inc/jira-harvest-time-tracker#50]
When stopping my timer in JIRA, it appears that the work log that gets generated is using the date and **time** when I stopped the timer.  Since the field in JIRA is called **Date Started**, this addon should keep track of the time I started my timer so that it can be used when stopping the timer.  This is a pretty important detail, especially when we need to know when employees started working.  By using the time when the timer was stopped, it's misleading and leads us to believe that employees started working later in the day.  This could potentially impact reports and our KPIs as well.

**Comment by kuya1284** [comment]
Updated the title of this issue.

**Comment by gabrielsomoza** [comment]
I understand what you mean, I'll take a look. Just to be clear, by "JIRA's Date Started field" do you mean 
A) Worklog's "Date Started" field, or
B) the Issue's?

**Comment by kuya1284** [comment]
Yes, I'm referring to the Worklog's Date Started field. Thanks.

**Comment by kellaferr24** [comment]
I have the same issue. How has this not been addressed?

**Comment by gabrielsomoza** [comment]
We're working on a fix for this ticket and a most of the other ones as well as part of a big re-design of the extension. We expect it to be ready Q4 this year.

We'll release back-port fixes for issues like this one as soon as we have them ready - we'll notify you via email and also via this ticket.
