### ISSUE TITLE
Ability to insert date via Jira

### ISSUE THREAD

**Issue by artturig** [Strategery-Inc/jira-harvest-time-tracker#51]
Nice plugin, just what our company needs. We have had this under testing for a while and so far good feedback from our team.

Is it on road map or could you add feature for the date also for the manual entry?

Plenty of times we have situation where you are able to log work only next day aka day later than work done. That will cause logs to be out of sync since we have to manually edit day from Harvester.

**Comment by sdishman** [comment]
This would be helpful for us as well.  Just this morning I realized that I accidentally left a time tracker running overnight.  This morning I fixed it by going through these steps:

1. Delete timer from Harvest
2. Go back into JIRA plugin and enter the time range.  JIRA then creates the work log for today, and adds to Harvest for today.
3. Go back into Harvest and change the time record from today to yesterday.

This leaves the JIRA worklog in a funky state though.  If in step 2 I could add yesterday's date, it would eliminate step 3 and fix the worklog issue automatically.

**Comment by gabrielsomoza** [comment]
We can certainly work on this feature. We'll keep in on the queue for future development. You'll get notified of any progress through this ticket.

Thanks for your suggestion!

**Comment by artturig** [comment]
Brilliant, thanks.

**Comment by vitorfragoso** [comment]
+1! In the project that I'm working right now, we are using harvest and jira and we have the same "problem" related here. This feature would be awesome.

**Comment by joannou** [comment]
+1

**Comment by gabrielsomoza** [comment]
Great to see more people are behind this idea, we'll push it up the priority list. Right now we're working on releasing the plugin for JIRA 7, then we'll shift focus back to new features.

**Comment by chris5287** [comment]
+1 any update available on this task?

**Comment by tott** [comment]
Hi there, we really need this as well for our cloud hosted version. Is there any chance to get an update on this task?

**Comment by gsomoza** [comment]
No updates yet, we're trying to sort some of the other urgent issues so this isn't scheduled yet.

**Comment by adamedgerton** [comment]
+1 to this being an important feature for our team

**Comment by symbiogenesis** [comment]
+1

**Comment by gsomoza** [comment]
The latest version of the Cloud plugin should support this feature now. We're working on back-porting it to JIRA Download.
