### ISSUE TITLE
Cannot connect to Harvest

### ISSUE THREAD

**Issue by ednoles** [Strategery-Inc/jira-harvest-time-tracker#53]
We've updated the SSL certificate, confirmed that we're on the latest version of the plugin, ran the debug console and are still getting the following error:

![screen shot 2015-09-01 at 9 45 16 am](https://cloud.githubusercontent.com/assets/14075772/9607568/7bb3c6a2-508f-11e5-9fa8-fed4d4ced4dc.png)

**Comment by gabrielsomoza** [comment]
Sorry to know about your issue. A few other people have been having similar issues but they're hard to reproduce and unfortunately we don't always get enough log information (e.g. company policies, etc). 

Any chance you could send us info from the debug console, JIRA logs and if possible the Network tab from your browser's devtools to support (at) strategery (dot) io ? The more information the better.

If you're on a Linux server with OpenSSL, please also make sure this command also works: `openssl s_client -connect [your-harvest-account].harvestapp.com:443` (it should connect). If it doesn't work we'd also appreciate it if you could send us input on any errors that you get.

**Comment by ednoles** [comment]
@gabrielsomoza is there a way I can send you files and add others to this ticket?

**Comment by ednoles** [comment]
Sending documentation to the Strategery Support email above.

**Comment by gabrielsomoza** [comment]
@ednoles we just released a new version of the plugin that has several stability improvements and bug-fixes. Could you update and check again to see if the issue was fixed?
