### ISSUE TITLE
Cannot connect to Harvest 'ERROR' message - Cloud Edition

### ISSUE THREAD

**Issue by sam-base** [Strategery-Inc/jira-harvest-time-tracker#55]
The plugin has stopped working today. We have tried to 'disable / enable', and 'unsubscribe / subscribe', but this has not fixed the issue.

Jira Billing still shows this as current subscription. Please advise on how this can be resolved.

![screenshot 2015-09-22 12 18 31](https://cloud.githubusercontent.com/assets/14753941/10017206/52575634-6124-11e5-811c-4907aabc90b9.png)
![screenshot 2015-09-22 12](https://cloud.githubusercontent.com/assets/14753941/10017266/ce55a506-6124-11e5-852f-ae81c97a9d15.png)

**Comment by gabrielsomoza** [comment]
Server was down - restored. Thanks for reporting!

**Comment by sam-base** [comment]
Thanks Gabriel


Sam Westlake / Project Director / Base
Tel: +44(0)1202 766 666

wearebase.com <http://www.wearebase.com/> / Home of ODL Bournemouth
<http://odl.wearebase.com/>, the world's largest free Device Lab and
redevelop.io, a one-day developer conference on the coast.

We Are Base Ltd is a registered company in England and Wales, Number
6663791 | VAT Number: 936 117 917 | More information at www.wearebase.com
