### ISSUE TITLE
Jira Cloud. Correct Harvest Project does not always appear in timesheets

### ISSUE THREAD

**Issue by estan1** [Strategery-Inc/jira-harvest-time-tracker#57]
Jira Cloud

Steps to reproduce:
1. Choose a project in Jira using the plugin button, then fill the rest and submit.
2. Look at the Harvest Timesheets, the project chosen is sometimes different than the one selected while using the plugin in Jira.

We have many projects in Jira and same in Harvest.

Can you help?

**Comment by gabrielsomoza** [comment]
@estan1 one of our servers is having issues again, we'll keep you updated here.

**Comment by damian-pastorini** [comment]
I wasn't able to replicate the issue, every time I choosed a project and started the timer that's what I see in the timesheet.
What I did noted is that when you click on the start button in a new ticket, the project selected by Harvest is a default one (like the first on the list or sometimes the last one used) and not the one you are in JIRA.
