### ISSUE TITLE
JIRA v7 support

### ISSUE THREAD

**Issue by benow** [Strategery-Inc/jira-harvest-time-tracker#58]
Any timeline when the plugin will be compatible with JIRA 7?

**Comment by gabrielsomoza** [comment]
Current roadmap:
* Release timeout fixes for several clients. That will happen today or tomorrow at the latest.
* Compatibility with JIRA 7.
* Rest of the roadmap as described by milestones and tickets.

**Comment by gabrielsomoza** [comment]
Quick update: there are several UI changes to JIRA 7 that make our plugin incompatible. We'll determine what's causing that and provide an ETA as soon as possible. 

Meanwhile, we'll release milestone 2.5.3 anyways.

**Comment by banar** [comment]
Can't wait to get an update for JIRA 7

**Comment by gabrielsomoza** [comment]
Dev team says things are looking good (despite a lack of good documentation). Looks like we'll be testing the JIRA 7 version within the next few days.

**Comment by kvarga** [comment]
Any update here? Need to upgrade JIRA this weekend and this is 1 of the 2 plugins we are concerned about

**Comment by gabrielsomoza** [comment]
Yes, got delayed on some issues but we might be able to release before the weekend. Will update this ticket when ready.

**Comment by gabrielsomoza** [comment]
Version 3 released with JIRA 7 support! Please update and let us know of any issues! Will close this ticket and we'll address any new issues on separate tickets.
