### ISSUE TITLE
[Cloud] Users have to login multiple times a day

### ISSUE THREAD

**Issue by gsomoza** [Strategery-Inc/jira-harvest-time-tracker#61]
Right now sessions are very short-lived and users report that they have to re-enter their Harvest credentials every day. This seems to happen on both Cloud and Download versions, so it could be related to the Harvest API..

What can we do to improve this using the current code-base?

**Comment by tott** [comment]
Is there any updated on when this will be available in the cloud version?

**Comment by gsomoza** [comment]
Is this happening to you on a cloud install? We didn't have this issue on cloud ourselves so it wasn't in the roadmap for that version of the plugin until now.

**Comment by tott** [comment]
Yes, this is related to a cloud install

**Comment by gsomoza** [comment]
Alright, we'll try to debug that as well then. 

If you're using Safari, could you take a look at #24, apply the same workaround suggested there, and then see if the issue persists? Let me know if it gets fixed cause that would confirm the source of the issue in the case of the Cloud platform.

**Comment by tott** [comment]
I'm actually using Chrome. Does it still make sense to try this with Safari? Can you point me to some things I could look at to provide more information to help you isolate this issue. Which is the Cookie i should look at that would control this behavior.

**Comment by gsomoza** [comment]
As far as we know 24 only applies to Safari. So if you're using Chrome but still experiencing this issue then its probably not the same thing. The cookie name should just be "session" - do you see it on your end?

**Comment by tott** [comment]
The session cookie actually looks quite ok but there is one more which seems to hold the account data and has an expiration which is very close - https://www.evernote.com/l/AAkd7T22AUNBUa3eXGWPiC1JtZ1eP8e5YR4B/image.png

**Comment by gsomoza** [comment]
Alright, thanks for this info. The expiration date is July 6th from what I see, so I'm not sure that's the problem.. especially if this is something that happens to you as often as every day.. I'll have a developer take a look at this anyways just in case. 

It will take a while for us to get this fixed though, based on our current roadmap. Unless we have other people reporting the same issue on Cloud, in which case we'll definitely escalate it.

**Comment by tott** [comment]
Thanks for checking. Really appreciate your help. And yes, it happens multiple times per day even when not restarting the browser.

**Comment by adamf321** [comment]
Any update on this? I have the same problem, also in Chrome. I have to log in almost every time I start or stop the timer.

**Comment by gsomoza** [comment]
We've finally come around to working on this, and hope to release an improved version during Q1 2017. Thanks for your patience and stay tuned.

**Comment by SeanPTaylor** [comment]
Do you have any visibility on when in Q1 you anticipate releasing the new versions? We are have experienced the same issue, but otherwise are very happy with what you have been able to do. Thanks so much.

**Comment by gsomoza** [comment]
Closing because this should be resolved in the latest versions of the plugin.
