### ISSUE TITLE
Servers down again. Plugin does not load for Jira Cloud

### ISSUE THREAD

**Issue by estan1** [Strategery-Inc/jira-harvest-time-tracker#63]
Hey guys,

We are with Jira Cloud. The plugin is down for more than 10 hours already. 
It does not load at all. As a result all our teams can not log time. This started to happen too often.

Can you guys please fix asap? What is the estimated time for fixing this?
Any long term solution here? 

Your official site/link for support is also down: https://usestrategery.com/
Where do you send support request when this happens? Here?

**Comment by gabrielsomoza** [comment]
More info on #62 (will keep that open), hopefully that will make sure it doesn't go down again anytime soon while we work on finding the issue or moving to a new server. Right now it looks like the latter will be the more likely solution.
