### ISSUE TITLE
Use Jira project code to pre-select correct Harvest project

### ISSUE THREAD

**Issue by chris5287** [Strategery-Inc/jira-harvest-time-tracker#64]
We use the same project codes for Jira and Harvest, so it would be great if the Jira plugin automatically selected the matching Harvest project when adding time.

**Comment by marks** [comment]
+1 yes please!

**Comment by andrewmallis** [comment]
+1000

**Comment by chris5287** [comment]
Any updates on when this feature may be implemented?

**Comment by gsomoza** [comment]
I'm trying to strike a balance between new features and saving money for rebuilding the plugin from scratch (see #44). This one should be a relatively safe addition so we might be able to get to it within the next two/three months - maybe sooner.

**Comment by mattvandam** [comment]
We would like to see this feature added also.  Any updates on time frames now?

**Comment by olegip** [comment]
Hi,
This feature is critical.
Developers are constantly complain about having to select the project over and over again.
Also in a lot of cases, they just forget to do so and the time is logged incorrectlyt to the first project in the list.

Thanks,
Oleg

**Comment by gsomoza** [comment]
UPDATE: we just released a few fixes for bugs that were seriously affecting the workflows of many people. We're still trying to squash a few remaining bugs before we shift gears towards rebuilding from scratch or adding features. Stay tuned, we know this feature would be very useful so it's at the top of our feature priorities.

**Comment by chris5287** [comment]
Any updates on when this feature may be implemented?

**Comment by gsomoza** [comment]
We're working on it right now for our Cloud version of the plugin, along several other changes, fixes and improvements.

**Comment by chris5287** [comment]
Thanks for the update, is there a timeline/roadmap for the Server version of the plugin?

**Comment by gsomoza** [comment]
Not currently, but if the cloud plugin is well received then we'll probably shift focus to the server version shortly thereafter. It could still take a while though..

**Comment by chris5287** [comment]
Ok, well I would certainly like to see the server version updated (and I don't think I'm the only one 😄!)

**Comment by gsomoza** [comment]
Good to know, and it's great to hear your feedback by the way: if more people showed interest like that, then we would be able to prioritise better!

**Comment by wbrands2** [comment]
+1 this is very important to us!

**Comment by gsomoza** [comment]
FYI we've been working already a few week on porting our plugin's brand-new Cloud version to JIRA On-Premise. Stay tuned for the release!

**Comment by nilesh-spinx** [comment]
Hello There,

This is very important us and it is increasing our daily task to monitor tasks are logged on correct projects.

Any ETA, by when this issue will be fixed? many time it happens that hours logs to the wrong project.

Will appreciate your solution

**Comment by gsomoza** [comment]
@nilesh-spinx @wbrands2  we released [a new plugin](https://marketplace.atlassian.com/apps/1219223/harvester-real-time-tracking?hosting=cloud&tab=overview) that does implement this functionality. For Cloud users we also released a new version with the complete rewrite as well, so it should be working there as well. If it's not, please let us know.

If you're already a customer please make sure to also read the following message: https://github.com/Strategery-Inc/jira-harvest-time-tracker/issues/90 – we'll send more info to existing customers via email soon.
