### ISSUE TITLE
Plugin won't finalize connecting

### ISSUE THREAD

**Issue by zamoose** [Strategery-Inc/jira-harvest-time-tracker#65]
I've experienced this on three separate Macs using Chrome (regular and Incognito) and Safari, using Mavericks and El Capitan. Symptoms are:

1. Able to click the "Track Time" button at which point I am
2. Presented with a log-in modal.
3. I enter the details for our Harvest install and my username and password and submit.
4. I see the progress bar and am then re-presented with the login modal.

I know I am using the correct Harvest info, as if I enter the wrong password, I see "Cannot connect to Harvest, please check your credentials". It just simply never seems to finalize when I type the correct password in.

Help?

**Comment by zamoose** [comment]
Looks like this may be related (obliquely or *explicitly*) to #24.

**Comment by gsomoza** [comment]
I just commented a possible workaround on that ticket - could you see if that fixes it for you?

**Comment by gsomoza** [comment]
Discussion about this has move to the referenced ticket.
