### ISSUE TITLE
Add time tracking to issue details views

### ISSUE THREAD

**Issue by tott** [Strategery-Inc/jira-harvest-time-tracker#69]
It would be really helpful to make the time tracking available in the Details view. In this case when you're working through a task list or on a sprint board you would not need to navigate to each individual task to track your time. This would improve the workflow a lot.

**Comment by gsomoza** [comment]
Unfortunately that's currently not possible on the cloud version as far as we know. Mentioning this because on another ticket you seemed to suggest your running on Cloud. Could you confirm if that's not the case?

For the "Download" version of the plugin this is already working.

**Comment by tott** [comment]
Correct, this is for the cloud version. Is there any time-frame when this feature might come to the cloud version?

**Comment by gsomoza** [comment]
No, there's not time-frame because I don't think its even possible for the Cloud version. But I'll take another look at the cloud API / capabilities to make sure.

**Comment by tott** [comment]
Thanks a lot for checking. I really appreciate the support.

**Comment by gsomoza** [comment]
This feature is supported now on the latest version of our plugin
