### ISSUE TITLE
Update existing issue time

### ISSUE THREAD

**Issue by chrisschaub** [Strategery-Inc/jira-harvest-time-tracker#70]
When you stop a timer and then restart it, a new timer entry is created in Harvest. Our users switch between tasks quite frequently, stop/start time. They will have a lot of entries in Harvest for each Jira Issue due to starting and stopping. Would there be a way to update the existing Harvest time entry if on the same day?

**Comment by gsomoza** [comment]
Unfortunately this isn't everyone's work-flow, some companies require high detail information on exactly when work started and stopped for each task, even if the task was worked on at multiple times during the same day. In situations like these I'm afraid we have to stick to the needs of those who need the most amount of data..

Closing the ticket for now, but we can continue the discussion regardless and re-open later if we find a good solution to this.

**Comment by chrisschaub** [comment]
Right, but that isn't everyone's workflow either. I'd say it's 50/50 maybe. How about an option to "append" to existing timer or "create new" timer? That way it would be configurable?

**Comment by gsomoza** [comment]
Even if its 50/50 we still have to stick to whichever workflow needs the highest amount of details/data - which in this case is the one that needs to track the start/stop times of each time the task is worked on. So you're right: the only way forward would be to add a feature like the one you mentioned.

But appending to an existing timer would be a very complicated feature to add for the following reasons:

1. There's no easy and reliable way for us to find which existing timer would be a good candidate to resume, especially if the timer notes have changed.
2. Therefore we'd have to allow the user to choose which timer to resume, which at the very least means major changes to the UI, which is not insignificant.
3. Additionally, there's the following concern: what happens to existing worklogs that already have an end-time in JIRA? They will quickly go out of sync when compared to the Harvest time-entries. We'd have to find a way to identify which one needs editing, and edit it once the timer is stopped. But there's no easy/reliable way to identify which worklog needs updating.
4. What happens with timers that span more than one day (e.g. started at 11pm and paused at 1am the following day)?

I'm afraid there are just too many complications that would stem from trying to implement a feature like that in this plugin.

I had a similar workflow as yours for a few projects. A possible workaround that worked very well for me would be to: 

1. Start the timer using JIRA (the first time only).
2. "Pause" it using Harvest.
3. "Resume" it using Harvest as well, using the same time-entry that was previously created.
4. To really "Stop" it (once you're ready to add the worklog to JIRA)
    1. Make sure the timer in Harvest  is running.
    2. Go to JIRA and stop it from there. 
    3. The worklog will be appended using the TOTAL time spent that day.

You'd essentially be "tricking" our JIRA plugin to think the timer was running all the time, when it was actually not. Once I did this a couple of times it became really easy to do this for that particular project. 

Would that be an option for you? I honestly don't see a reliable way of adding this other feature at the moment..
