### ISSUE TITLE
Want to Contribute / Improve this Plugin?

### ISSUE THREAD

**Issue by gsomoza** [Strategery-Inc/jira-harvest-time-tracker#72]
Due to the cost of adding new features to this plugin (both for the OnDemand and Download versions) we're considering opening contributions to those interested.

The idea, for the time being, is to open contributions only to select companies/people. This will take us a step closer to fully open-sourcing the code, but without the risks of doing so: we will be able to vet who has access to the code.

Regardless of how exactly we approach this, we will always review all contributions thoroughly to ensure features work as intended and out users information remains safe.

Contributors will get:
1. Access to the code of either the OnDemand or Download version of the plugin for JIRA.
2. A license to use the plugin for free for one year. Significant contributions might be rewarded with an unlimited license.
3. Accreditation: we will list the changes and contact info of the contributor in the release notes. Significant contributors can also be listed in the `README.md` and other places with visibility.

If you're interested in contributing please leave a comment with some information about your experience developing Atlasssian plugins, ideally with links to code that we can review. You can send references / code privately via email: _gabriel (at) strategery (dot) io_ and if you're into it you can [get my GPG key here](https://somoza.keybase.pub/security_stuff/gabriel.public.gpg-key).

**Comment by mattvandam** [comment]
We would be interested in participating at a contributor to improve this plug-in.  We utilize Jira and Harvest heavily for our team and would like to see improvements in this plug-in.  I will contact you privately with information about our team and experience.

**Comment by gsomoza** [comment]
Closing: we decided pursuing this option is complicated on several levels, since this is a billed plugin.
