### ISSUE TITLE
Add time logs directly, without the timer

### ISSUE THREAD

**Issue by gabrielz** [Strategery-Inc/jira-harvest-time-tracker#75]
It would be very important for my team to have the ability to not use the "clock", but simply type in the time worked. Editing the time logged when stopping the clock would be enough (but not the ideal UX).
Is this possible in any way?
Thank you.

**Comment by gsomoza** [comment]
You should be able to input time "after the fact" by just typing the amount of time spent before starting the timer. Then click on the button and the time will be submitted (instead of starting a timer). Is that what you need?
