### ISSUE TITLE
Is there a way to save the host URL for Harvest

### ISSUE THREAD

**Issue by leehylton-bsi** [Strategery-Inc/jira-harvest-time-tracker#76]
My team all logs time to our Harvest site and it would be nice if we could prefill that form for everyone.  As it stands now it seems to depend on the browser cache or you have to fill it out each time to make the connection.

**Comment by gsomoza** [comment]
There's currently no way of doing it, but we're working on that for our next release - as it's one of the most requested features. I'll update this ticket once it's ready, which if all goes well should be Q1 2017

**Comment by leehylton-bsi** [comment]
Thanks, look forward to it!

**Comment by gsomoza** [comment]
This feature should be available for a while now. Closing this ticket, but please re-open or file a new one if you see any bugs.
