### ISSUE TITLE
Allow User to type Integer or Decimal Values in the Hours Field

### ISSUE THREAD

**Issue by wbrands2** [Strategery-Inc/jira-harvest-time-tracker#88]
Current format is 0:00, could it be configurable to allow integer or decimal values. 

Error message given:
> Invalid hours format, please use hh:mm

**Comment by gsomoza** [comment]
Thanks for reporting @wbrands2 . Quick question: which version of JIRA are you using (Cloud / Download)?

**Comment by wbrands2** [comment]
Download

**Comment by gsomoza** [comment]
Download will receive an update in the next month or two, with this feature included. I'll close the ticket then so you get notified.

**Comment by markadrake** [comment]
Hello @gsomoza what is the status of this feature? Also, are there opportunities to work together / collaborate to bring improvements to this product? Should I capture "feature requests" like this as issues?

**Comment by gsomoza** [comment]
@markadrake could you email me on gabriel (at) strategery (dot) io to discuss collaboration?

**Comment by gsomoza** [comment]
This feature should be working on the new version of the Download plugin (Harvester Time-Tracker).
