### ISSUE TITLE
Invalid Authorization Request bad_request 

### ISSUE THREAD

**Issue by carrchr** [Strategery-Inc/jira-harvest-time-tracker#92]
**Describe the bug**
Sign Into Harvest from JIRA issue fails with **Invalid Authorization Request** bad_request

**To Reproduce**
1. Download & Install Add-on
2. Configure Add-on with Oauth info created in harvest app.com
3. Click "Sign Into Harvest" button on a JIRA issue
4. New browser window opens up that is apparently trying to login to harvest which then displays an error Invalid Authorization Request bad_request    `https://michigansoftwarelabs.harvestapp.com/oauth2/authorize?response_type=token&client_id={redacted}&prompt=none&state=test-state&redirect_uri=https://{redacted}/plugins/servlet/com.strategery.jira-harvest/auth-popup`

**Expected behavior**
Login to Harvest

**Screenshots**
![screenshot](https://i.imgur.com/Vw05qqT.png)

**Browser Console Logs**
Nothing related to JIRA or Harvest

**Please complete the following information:**
 - JIRA Type: Server
 - JIRA Version: 7.12.1
 - Browser Type: Chrome on macOS 10.14
 - Browser Version: 72.0.3626.109

**Additional context**
tried in Safari (with which I had never logged in to `harvestapp.com`, I was prompted to sign-in to Harvest, I clicked use Google (that is what we are trying out, using our G Suite credentials) and then ended up at the same **Invalid Authorization Request** bad_request

**Comment by gsomoza** [comment]
Hi Chris, thanks for the detailed report. I'll do what I can to help you ASAP. Could you please email the redacted info (at least the contents for the redirect_uri parameter) to gabriel (at) strategery (dot) io?

**Comment by carrchr** [comment]
Hello Gabriel- turns out that the authentication from our JIRA to our new Harvest Time Tracking account wasn't working because when I created the OAuth key I was not ad "admin user" on Harvest. We re-created the OAuth credentials and re-configured our JIRA server and now it works.

**Comment by gsomoza** [comment]
Thanks a lot for getting back to us on this: it's good to know about this important "gotcha"!
