### ISSUE TITLE
Jira v8 Support?

### ISSUE THREAD

**Issue by ianrushton-tl** [Strategery-Inc/jira-harvest-time-tracker#93]
I have just gone to upgrade our version of servicedesk from 7.13.1 to 8.0.2 - and on the update check, it said that this plugin is incompatible.  It seems that nothing has really happened on the development of this app since last year - will it support v8 currently or in the future or do we need to source another plugin?

**Comment by gsomoza** [comment]
@ianrushton-tl could you please confirm which version you're running? You can also email me with the details of your license (SEN): gabriel (at) strategery (dot) io

**Comment by ianrushton-tl** [comment]
@gsomoza we are currently using JIRA servicedesk (server edition) v3.13.1, which is based on JIRA 7.10.1.  We are using the latest version of your plugin, and we are wishing to upgrade to Servicedesk 4.0.2, which is based upon JIRA 8.0.2.

I will send you out license details directly.

**Comment by gsomoza** [comment]
Based on your license it looks like you're using the old version of our plugin. I sent you details about the new version and how to transfer the license via email, so I'll close this ticket for now.
