### ISSUE TITLE
When 'Start Timer' is running for more than 5-10 mins, Jira typing, navigation slows down significantly

### ISSUE THREAD

**Issue by sgoljerova** [Strategery-Inc/jira-harvest-time-tracker#97]
**Describe the bug**
When 'Start Timer' is running for more than 5-10 mins, Jira typing, navigation slows down significantly

**To Reproduce**
1. Go to Jira and click on 'Issue'
2. Click on 'Start Timer'
3. Wait for 5-10 mins
4. Return to the Jira Issue
5. Click on 'Comment' and start typing in a comment.  Notice delay in letters appearing on the screen.
6. stop Timer.  Notice, no more delay in typing.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Be careful to blur or paint over any sensitive information. If you prefer, you can instead email them to support (at) strategery (dot) io

**Browser Console Logs**
After reporting the issue, whenever possible, please send us an email to support (at) strategery (dot) io including your [browser console log](https://kb.mailster.co/how-can-i-open-the-browsers-console/) output when the error happened. This will help us find the issue much faster and provide an accurate bug fix.

**Please complete the following information:**
 - JIRA Type: Jira Server
 - JIRA Version: v7.6.2
 - Browser Type: Chrome, Firefox
 - Browser Version: latest

**Additional context**

**Comment by sgoljerova** [comment]
Can you confirm the issue?

**Comment by mwoffenden** [comment]
Don't hold your breath.  Unfortunately this vendor is AWOL.  I submitted an issue a month ago, no response!  I'll likely be un-installing it soon.

**Comment by pwittke** [comment]
The latest version 1.0.16-SNAPSHOT (Released 2019-09-18) totally fixed this issue for us. CPU load went from 100% to 0.1% in Chrome.
